version: "3.9"

services:

  backend:
    container_name: iris-back
    build:
      context: ./backend
    image: iris-backend:local
    ports:
      - "8001:8001"
    networks:
      - iris-net

  frontend:
    container_name: iris-front
    build:
      context: ./frontend
    image: iris-frontend:local
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: "http://iris-back:8001"
    depends_on:
      - backend
    networks:
      - iris-net

networks:
  iris-net:
    driver: bridge
